# Creation of a table of contents and refrencing take
# more than one compilation round... Take a look here:
# https://tex.stackexchange.com/questions/301103/empty-table-of-contents
all:
	pdflatex Intro_to_sym.tex
	pdflatex Intro_to_sym.tex
	rm -rf *.aux *.log *.toc
